### ISSUE TITLE
chrome.tabs.query returns a empty array

### ISSUE THREAD

**Issue by lauaall** [ksucpea/marketplacehelper#3]
Hey, I know this is a WIP.
The panel.js cannot find the current url. I see that you have used `chrome.tabs.query` to get the url and Chrome API is returning tabs as a empty array. I googled this error code and found a StackOverflow thread about this 
![image](https://github.com/ksucpea/marketplacehelper/assets/48836917/ac4d0fa8-ce27-4d99-ab5a-81befd80c250)
I notice that you have not added `active:true`as a option into the query after I add it I still get the same error.
![image](https://github.com/ksucpea/marketplacehelper/assets/48836917/38e348b5-4e92-4889-8c20-80bcb64c33fd)
I have not yet found a fix to this problem. I also found that there is a Chromium bug report that has not been fixed yet.(https://issues.chromium.org/issues/41160154)
Also i rewrote the #start function to include error  messaging(will make a pull request).

```
document.querySelector("#start").addEventListener("click", function (e) {
         chrome.tabs.query({ active: true, currentWindow: true, lastFocusedWindow: true }, function (tabs) {
             if (!tabs || tabs.length === 0) {
                console.error("No active tab found");
                 return;
             }
            
             const activeTab = tabs[0];
             if (!activeTab.url) {
                 console.error("The active tab has no URL");
                 return;
             }
    
             const save = document.querySelector("#save-under").value;
             chrome.storage.local.get("saved", storage => {
                 if (!storage.saved || !Array.isArray(storage.saved)) {
                     console.error("No saved storage found or it's not an array");
                     return;
                 }
    
                 for (let i = 0; i < storage.saved.length; i++) {
                     if (storage.saved[i].name === save) {
                         if (!storage.saved[i].pathnames.includes(activeTab.url)) {
                             storage.saved[i].pathnames.push(activeTab.url);
                             chrome.storage.local.set({ "saved": storage.saved });
                         }
                         break;
                     }
                 }
                 sendMessage({ "type": "start", "name": save });
                 e.target.classList.add("active");
                 document.querySelector("#pause").classList.remove("active");
             });
         });
     });
```

**Comment by lauaall** [comment]
okay, update got the tab selector working
![image](https://github.com/ksucpea/marketplacehelper/assets/48836917/938c2819-149f-4223-a345-6fd714d0654b)

**Comment by lauaall** [comment]
potential workaround using Devtools Tab title
![image](https://github.com/ksucpea/marketplacehelper/assets/48836917/4d6080ef-bf2d-4503-a2cc-1cf9a785ae14)

```
chrome.tabs.getCurrent(function(tab) {
                    if (tab) {
                        // Extract the URL from the tab's title (assuming title is in the format "DevTools - www.facebook.com/marketplace/?ref=app_tab")
                        let tabTitle = tab.title;
                        let url = tabTitle.split(' - ')[1];
                        console.log(url)
                        if (url) {
                            tabs = [];
                            tabs.push({ url: url });
                        } 
                    } 
                });
                 return;
             }

```

**Comment by ksucpea** [comment]
I think it might be because your devtools are set to open in a new window instead of docked inside the page. Could you check and see if changing that helps? (You don't have to keep it like that but just to see if it is the issue)

![scrn](https://github.com/ksucpea/marketplacehelper/assets/59516750/905f6e43-b17b-43ba-83b4-67a0845b14eb)

Also, assuming that is the cause of the problem, would it help to query the tab by the url instead of querying by active?
Like this:
`chrome.tabs.query({ url: ["https://www.facebook.com/marketplace/*"] }, function (tabs)`

**Comment by lauaall** [comment]
im not at my pc rn will be back in about 1h

**Comment by lauaall** [comment]
![image](https://github.com/ksucpea/marketplacehelper/assets/48836917/182177c1-c090-4985-9049-bc73294ad873)
so the scanner works but the items are not displayed on the devtools windows

**Comment by ksucpea** [comment]
Yeah I just checked for myself and it isn't working for some reason... it was working before lol but I'll see if I can look into this later and fix it.

**Comment by lauaall** [comment]
Thats the bonus of writing code :)

**Comment by lauaall** [comment]
checking chrome extension errors might help
![image](https://github.com/ksucpea/marketplacehelper/assets/48836917/eb6c1537-1fbd-43a7-9318-63063554ffdc)

**Comment by lauaall** [comment]
im debugging too currently

**Comment by ksucpea** [comment]
Looks like for whatever reason facebook made it so that the item's listing photos are now retrieved in a separate API call and the entire remaining item data is in another call. My guess is that since it's processed async it's running into some sync issues and the photos are left out, causing this error. Not sure how to go about fixing this

**Comment by lauaall** [comment]
damn, thats unfortunate.

**Comment by lauaall** [comment]
All of the other info tools I found were using Python and Puppeteer, which is really slow.

**Comment by lauaall** [comment]
I'm thinking of removing the image part for now, and just showing prices, titles and descriptions. The whole query code has to be probably refactored.

**Comment by lauaall** [comment]
Closing as now immediate fix is available

**Comment by lauaall** [comment]
Closing as now immediate fix is available

**Comment by ksucpea** [comment]
I think I might be close to having a fix, it didn't require much changing, but I'm still working on it

**Comment by lauaall** [comment]
> I think I might be close to having a fix, it didn't require much changing, but I'm still working on it

Good, I would assist you, but I have no experience with any Facebook API

**Comment by ksucpea** [comment]
Just updated it, could you give it a try?

**Comment by lauaall** [comment]
Great, add a buymeacoffe link into readme aswell if anyone wants to support this
